# Generated by Django 5.1.3 on 2024-12-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_favorites_watchlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
